# Generated by Django 5.1.3 on 2024-12-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='product_video',
            new_name='shoes_video',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_tr',
        ),
        migrations.AlterField(
            model_name='shoes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='store.category'),
        ),
    ]
